version: "3.8"

services:


  admin:
    build:
      context: Admin
      dockerfile: Dockerfile
    volumes:
      - .:/admindata
    ports:
      - 5000:5000
    image: admin
    container_name: admin
    #command: python3 app.py 0.0.0.0:5000
    depends_on:
      - postgres


  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      #- .data/db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    container_name: some-postgres

