apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspire
  namespace: default
  labels:
    app: inspire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspire
  template:
    metadata:
      labels:
        app: inspire
    spec:
      containers:
      - name: inspire
        image: 428253719401.dkr.ecr.eu-west-1.amazonaws.com/inspire:latest


---
apiVersion: v1
kind: Service
metadata:
  name: inspire-service
  namespace: default
  labels:
    app: inspire
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30005
  selector:
    app: inspire
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: postgres-config
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: postgres-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-config
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
